apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-tracker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: performance-tracker
  template:
    metadata:
      labels:
        app: performance-tracker
    spec:
      containers:
        - name: performance-tracker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_PATH
              value: {{ .Values.env.DATABASE_PATH }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: HOST
              value: {{ .Values.env.HOST }}
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}
